<a href="https://colab.research.google.com/github/mohanQAEngineer/Cross-market-analysis/blob/main/Cross_market_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Installing requests

In [1]:
pip install requests

Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests) (2026.6.17)

#1.Crypto currencies

In [2]:
import requests
records=[]
for i in range(1,6):
    url="https://api.coingecko.com/api/v3/coins/markets?vs_currency=inr&per_page=250&order=market_cap_desc&page=1&sparkline=False"
    response=requests.get(url)
    if response.status_code==200:
        data=response.json()
        records.extend(data)
        print(f"page{i} fetched successfully.records:{len(data)}")
    else:
        print(f"failed to fetch page{i}.status code:{response.status_code}")
print(f"\ntotal records fetched:{len(records)}")

page1 fetched successfully.records:250
page2 fetched successfully.records:250
page3 fetched successfully.records:250
page4 fetched successfully.records:250
page5 fetched successfully.records:250

total records fetched:1250

#Installing pandas

In [3]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

#Converting into a dataframe

In [4]:
import pandas as pd

crypto_df=pd.DataFrame(records)
crypto_df

,id,symbol,name,image,current_price,market_cap,market_cap_rank,fully_diluted_valuation,total_volume,high_24h,...,total_supply,max_supply,ath,ath_change_percentage,ath_date,atl,atl_change_percentage,atl_date,roi,last_updated
0,bitcoin,btc,Bitcoin,https://coin-images.coingecko.com/coins/images...,6021958.00,120780718016767,1,120780718016767,2.503460e+12,6027835.00,...,2.005413e+07,2.100000e+07,11187013.00,-46.16704,2025-10-06T18:57:42.558Z,3993.420000,1.507056e+05,2013-07-05T00:00:00.000Z,None,2026-07-09T18:04:14.300Z
1,ethereum,eth,Ethereum,https://coin-images.coingecko.com/coins/images...,166752.00,20125578725133,2,20125578725133,6.530638e+11,167541.00,...,1.206831e+08,NaN,431946.00,-61.39503,2025-08-24T19:21:03.333Z,28.130000,5.926662e+05,2015-10-20T00:00:00.000Z,"{'times': 36.02241146332671, 'currency': 'btc'...",2026-07-09T18:04:11.063Z
2,tether,usdt,Tether,https://coin-images.coingecko.com/coins/images...,95.30,17563324714594,3,18084324446422,3.771678e+12,95.85,...,1.897620e+11,NaN,105.52,-9.67283,2025-01-25T16:51:57.989Z,36.860000,1.585815e+02,2015-03-02T00:00:00.000Z,None,2026-07-09T18:04:01.176Z
3,binancecoin,bnb,BNB,https://coin-images.coingecko.com/coins/images...,54490.00,7344699722027,4,7344699722027,4.810700e+10,54828.00,...,1.347822e+08,2.000000e+08,121422.00,-55.12340,2025-10-13T08:41:24.131Z,2.580000,2.108047e+06,2017-10-19T00:00:00.000Z,None,2026-07-09T18:04:13.370Z
4,usd-coin,usdc,USDC,https://coin-images.coingecko.com/coins/images...,95.36,6993756631508,5,6993955746094,1.094599e+12,95.87,...,7.334406e+10,NaN,96.98,-1.66300,2026-05-20T14:19:58.071Z,65.310000,4.602658e+01,2021-05-19T13:14:05.611Z,None,2026-07-09T18:04:08.885Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1245,astherus-usdf,usdf,Aster USDF,https://coin-images.coingecko.com/coins/images...,95.25,10786145973,246,10786145973,7.894920e+05,95.79,...,1.132437e+08,NaN,96.77,-1.56920,2026-05-20T14:15:24.188Z,70.870000,3.439748e+01,2025-10-10T21:23:15.100Z,None,2026-07-09T18:04:06.022Z
1246,spacex-bstocks-tokenized-stock,spcxb,SpaceX (bStocks Tokenized Stock),https://coin-images.coingecko.com/coins/images...,14539.76,10699479220,247,10699479220,3.744043e+09,14598.29,...,7.358696e+05,NaN,21458.00,-32.23964,2026-06-16T01:01:03.420Z,13918.180000,4.466850e+00,2026-07-08T18:56:43.802Z,None,2026-07-09T18:03:53.726Z
1247,derive,drv,Derive,https://coin-images.coingecko.com/coins/images...,10.59,10588239072,248,15886263406,3.318828e+07,10.70,...,1.500000e+09,1.500000e+09,19.75,-46.39283,2025-01-15T03:52:14.666Z,1.068000,8.918579e+02,2025-04-07T13:06:12.300Z,None,2026-07-09T18:04:13.577Z
1248,rollbit-coin,rlb,Rollbit Coin,https://coin-images.coingecko.com/coins/images...,6.50,10564333640,249,10564544316,2.602416e+07,6.56,...,1.624117e+09,5.000000e+09,22.02,-70.45862,2023-11-11T17:10:05.473Z,0.073824,8.711335e+03,2022-07-02T02:46:34.730Z,None,2026-07-09T18:03:57.769Z
1249,tradable-na-third-party-online-merchant-sstn,pc0000015,Tradable NA Third Party Online Merchant SSTN,https://coin-images.coingecko.com/coins/images...,95.38,10513798802,250,10513798802,NaN,95.93,...,1.102260e+08,3.500000e+08,97.01,-1.68005,2026-05-20T14:20:10.699Z,85.320000,1.179956e+01,2025-07-04T05:20:06.597Z,None,2026-07-09T17:55:17.661Z

#Filter using pandas

In [ ]:
crypto_df.head()

,id,symbol,name,image,current_price,market_cap,market_cap_rank,fully_diluted_valuation,total_volume,high_24h,...,total_supply,max_supply,ath,ath_change_percentage,ath_date,atl,atl_change_percentage,atl_date,roi,last_updated
0,bitcoin,btc,Bitcoin,https://coin-images.coingecko.com/coins/images...,5893946.00,118174589586707,1,118174648523292,4.198997e+12,5911787.00,...,2.005115e+07,21000000.0,11187013.00,-47.31439,2025-10-06T18:57:42.558Z,3993.42,1.474915e+05,2013-07-05T00:00:00.000Z,None,2026-07-02T17:15:29.040Z
1,ethereum,eth,Ethereum,https://coin-images.coingecko.com/coins/images...,162092.00,19561093350325,2,19561093350325,1.376242e+12,163601.00,...,1.206833e+08,NaN,431946.00,-62.47405,2025-08-24T19:21:03.333Z,28.13,5.760982e+05,2015-10-20T00:00:00.000Z,"{'times': 35.797000291414754, 'currency': 'btc...",2026-07-02T17:15:29.044Z
2,tether,usdt,Tether,https://coin-images.coingecko.com/coins/images...,95.42,17584278815640,3,18105914931465,6.209555e+12,95.43,...,1.897568e+11,NaN,105.52,-9.84104,2025-01-25T16:51:57.989Z,36.86,1.581000e+02,2015-03-02T00:00:00.000Z,None,2026-07-02T17:15:28.397Z
3,binancecoin,bnb,BNB,https://coin-images.coingecko.com/coins/images...,53631.00,7228401319508,4,7228401319508,8.040221e+10,53898.00,...,1.347826e+08,200000000.0,121422.00,-55.83087,2025-10-13T08:41:24.131Z,2.58,2.074812e+06,2017-10-19T00:00:00.000Z,None,2026-07-02T17:15:29.181Z
4,usd-coin,usdc,USDC,https://coin-images.coingecko.com/coins/images...,95.49,7006464244108,5,7006497612417,1.327947e+12,95.50,...,7.337146e+10,NaN,96.98,-1.82497,2026-05-20T14:19:58.071Z,65.31,4.578605e+01,2021-05-19T13:14:05.611Z,None,2026-07-02T17:15:13.567Z

#Retriving the crypto currency data frame

In [ ]:
crypto_df

,id,symbol,name,image,current_price,market_cap,market_cap_rank,fully_diluted_valuation,total_volume,high_24h,...,total_supply,max_supply,ath,ath_change_percentage,ath_date,atl,atl_change_percentage,atl_date,roi,last_updated
0,bitcoin,btc,Bitcoin,https://coin-images.coingecko.com/coins/images...,5.893946e+06,118174589586707,1,118174648523292,4.198997e+12,5.911787e+06,...,2.005115e+07,2.100000e+07,1.118701e+07,-47.31439,2025-10-06T18:57:42.558Z,3993.420000,1.474915e+05,2013-07-05T00:00:00.000Z,None,2026-07-02T17:15:29.040Z
1,ethereum,eth,Ethereum,https://coin-images.coingecko.com/coins/images...,1.620920e+05,19561093350325,2,19561093350325,1.376242e+12,1.636010e+05,...,1.206833e+08,NaN,4.319460e+05,-62.47405,2025-08-24T19:21:03.333Z,28.130000,5.760982e+05,2015-10-20T00:00:00.000Z,"{'times': 35.797000291414754, 'currency': 'btc...",2026-07-02T17:15:29.044Z
2,tether,usdt,Tether,https://coin-images.coingecko.com/coins/images...,9.542000e+01,17584278815640,3,18105914931465,6.209555e+12,9.543000e+01,...,1.897568e+11,NaN,1.055200e+02,-9.84104,2025-01-25T16:51:57.989Z,36.860000,1.581000e+02,2015-03-02T00:00:00.000Z,None,2026-07-02T17:15:28.397Z
3,binancecoin,bnb,BNB,https://coin-images.coingecko.com/coins/images...,5.363100e+04,7228401319508,4,7228401319508,8.040221e+10,5.389800e+04,...,1.347826e+08,2.000000e+08,1.214220e+05,-55.83087,2025-10-13T08:41:24.131Z,2.580000,2.074812e+06,2017-10-19T00:00:00.000Z,None,2026-07-02T17:15:29.181Z
4,usd-coin,usdc,USDC,https://coin-images.coingecko.com/coins/images...,9.549000e+01,7006464244108,5,7006497612417,1.327947e+12,9.550000e+01,...,7.337146e+10,NaN,9.698000e+01,-1.82497,2026-05-20T14:19:58.071Z,65.310000,4.578605e+01,2021-05-19T13:14:05.611Z,None,2026-07-02T17:15:13.567Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1245,nexus-4,nex,Nexus,https://coin-images.coingecko.com/coins/images...,1.762000e-04,10571151677,246,17618586128,3.899914e+07,1.765700e-04,...,1.000000e+14,1.000000e+14,6.627700e-04,-73.48227,2026-05-21T08:50:44.565Z,0.000172,2.140660e+00,2026-07-01T08:51:12.727Z,None,2026-07-02T17:15:25.304Z
1246,gmt-token,gomining,GoMining Token,https://coin-images.coingecko.com/coins/images...,2.607000e+01,10532933052,247,10532933052,9.898908e+08,2.620000e+01,...,4.040316e+08,4.369152e+08,4.804000e+01,-46.03411,2025-08-10T20:21:25.098Z,5.650000,3.586658e+02,2022-11-10T00:18:31.110Z,None,2026-07-02T17:15:24.642Z
1247,tradable-na-third-party-online-merchant-sstn,pc0000015,Tradable NA Third Party Online Merchant SSTN,https://coin-images.coingecko.com/coins/images...,9.551000e+01,10529275190,248,10529275190,NaN,9.552000e+01,...,1.102260e+08,3.500000e+08,9.701000e+01,-1.83476,2026-05-20T14:20:10.699Z,85.320000,1.162364e+01,2025-07-04T05:20:06.597Z,None,2026-07-02T17:15:23.514Z
1248,pearl-2,prl,Pearl,https://coin-images.coingecko.com/coins/images...,4.483000e+01,10462359776,249,94148110321,7.647087e+07,4.756000e+01,...,2.100000e+09,2.100000e+09,8.302000e+01,-46.14618,2026-06-01T22:12:26.760Z,35.230000,2.691381e+01,2026-06-14T10:29:43.542Z,None,2026-07-02T17:15:22.469Z
1249,avant-usd,avusd,Avant USD,https://coin-images.coingecko.com/coins/images...,9.548000e+01,10359208555,250,10359208555,2.874810e+05,9.553000e+01,...,1.084905e+08,NaN,1.027300e+02,-7.30477,2026-05-19T15:20:09.996Z,83.810000,1.361407e+01,2025-05-02T06:32:03.463Z,None,2026-07-02T17:15:11.858Z

#converting timestamp into datetime

In [5]:
crypto_df['last_updated']=pd.to_datetime(crypto_df['last_updated']).dt.date

#Checking data types,null values of the crypto dataframe

In [6]:
crypto_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1250 entries, 0 to 1249
Data columns (total 26 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   id                                1250 non-null   object
 1   symbol                            1250 non-null   object
 2   name                              1250 non-null   object
 3   image                             1250 non-null   object
 4   current_price                     1250 non-null   float64
 5   market_cap                        1250 non-null   int64
 6   market_cap_rank                   1250 non-null   int64
 7   fully_diluted_valuation           1250 non-null   int64
 8   total_volume                      1180 non-null   float64
 9   high_24h                          1240 non-null   float64
 10  low_24h                           1240 non-null   float64
 11  price_change_24h                  1240 non-null   float64
 12  price_change_percentage_24h       1240 non-null   float64
 13  market_cap_change_24h             1240 non-null   float64
 14  market_cap_change_percentage_24h  1240 non-null   float64
 15  circulating_supply                1250 non-null   float64
 16  total_supply                      1250 non-null   float64
 17  max_supply                        710 non-null    float64
 18  ath                               1250 non-null   float64
 19  ath_change_percentage             1250 non-null   float64
 20  ath_date                          1250 non-null   object
 21  atl                               1250 non-null   float64
 22  atl_change_percentage             1250 non-null   float64
 23  atl_date                          1250 non-null   object
 24  roi                               135 non-null    object
 25  last_updated                      1250 non-null   object
dtypes: float64(15), int64(3), object(8)
memory usage: 254.0+ KB

#Converting last_updated column from object to proper date

In [7]:
crypto_df['last_updated']=pd.to_datetime(crypto_df['last_updated'])
print(crypto_df)
print(crypto_df.dtypes)

                                                id     symbol  \
0                                          bitcoin        btc
1                                         ethereum        eth
2                                           tether       usdt
3                                      binancecoin        bnb
4                                         usd-coin       usdc
...                                            ...        ...
1245                                 astherus-usdf       usdf
1246                spacex-bstocks-tokenized-stock      spcxb
1247                                        derive        drv
1248                                  rollbit-coin        rlb
1249  tradable-na-third-party-online-merchant-sstn  pc0000015

                                              name  \
0                                          Bitcoin
1                                         Ethereum
2                                           Tether
3                                              BNB
4                                             USDC
...                                            ...
1245                                    Aster USDF
1246              SpaceX (bStocks Tokenized Stock)
1247                                        Derive
1248                                  Rollbit Coin
1249  Tradable NA Third Party Online Merchant SSTN

                                                  image  current_price  \
0     https://coin-images.coingecko.com/coins/images...     6021958.00
1     https://coin-images.coingecko.com/coins/images...      166752.00
2     https://coin-images.coingecko.com/coins/images...          95.30
3     https://coin-images.coingecko.com/coins/images...       54490.00
4     https://coin-images.coingecko.com/coins/images...          95.36
...                                                 ...            ...
1245  https://coin-images.coingecko.com/coins/images...          95.25
1246  https://coin-images.coingecko.com/coins/images...       14539.76
1247  https://coin-images.coingecko.com/coins/images...          10.59
1248  https://coin-images.coingecko.com/coins/images...           6.50
1249  https://coin-images.coingecko.com/coins/images...          95.38

           market_cap  market_cap_rank  fully_diluted_valuation  total_volume  \
0     120780718016767                1          120780718016767  2.503460e+12
1      20125578725133                2           20125578725133  6.530638e+11
2      17563324714594                3           18084324446422  3.771678e+12
3       7344699722027                4            7344699722027  4.810700e+10
4       6993756631508                5            6993955746094  1.094599e+12
...               ...              ...                      ...           ...
1245      10786145973              246              10786145973  7.894920e+05
1246      10699479220              247              10699479220  3.744043e+09
1247      10588239072              248              15886263406  3.318828e+07
1248      10564333640              249              10564544316  2.602416e+07
1249      10513798802              250              10513798802           NaN

        high_24h  ...  total_supply    max_supply          ath  \
0     6027835.00  ...  2.005413e+07  2.100000e+07  11187013.00
1      167541.00  ...  1.206831e+08           NaN    431946.00
2          95.85  ...  1.897620e+11           NaN       105.52
3       54828.00  ...  1.347822e+08  2.000000e+08    121422.00
4          95.87  ...  7.334406e+10           NaN        96.98
...          ...  ...           ...           ...          ...
1245       95.79  ...  1.132437e+08           NaN        96.77
1246    14598.29  ...  7.358696e+05           NaN     21458.00
1247       10.70  ...  1.500000e+09  1.500000e+09        19.75
1248        6.56  ...  1.624117e+09  5.000000e+09        22.02
1249       95.93  ...  1.102260e+08  3.500000e+08        97.01

      ath_change_percentage                  ath_date           atl  \
0                 -46.16704  2025-10-06T18:57:42.558Z   3993.420000
1                 -61.39503  2025-08-24T19:21:03.333Z     28.130000
2                  -9.67283  2025-01-25T16:51:57.989Z     36.860000
3                 -55.12340  2025-10-13T08:41:24.131Z      2.580000
4                  -1.66300  2026-05-20T14:19:58.071Z     65.310000
...                     ...                       ...           ...
1245               -1.56920  2026-05-20T14:15:24.188Z     70.870000
1246              -32.23964  2026-06-16T01:01:03.420Z  13918.180000
1247              -46.39283  2025-01-15T03:52:14.666Z      1.068000
1248              -70.45862  2023-11-11T17:10:05.473Z      0.073824
1249               -1.68005  2026-05-20T14:20:10.699Z     85.320000

      atl_change_percentage                  atl_date  \
0              1.507056e+05  2013-07-05T00:00:00.000Z
1              5.926662e+05  2015-10-20T00:00:00.000Z
2              1.585815e+02  2015-03-02T00:00:00.000Z
3              2.108047e+06  2017-10-19T00:00:00.000Z
4              4.602658e+01  2021-05-19T13:14:05.611Z
...                     ...                       ...
1245           3.439748e+01  2025-10-10T21:23:15.100Z
1246           4.466850e+00  2026-07-08T18:56:43.802Z
1247           8.918579e+02  2025-04-07T13:06:12.300Z
1248           8.711335e+03  2022-07-02T02:46:34.730Z
1249           1.179956e+01  2025-07-04T05:20:06.597Z

                                                    roi  last_updated
0                                                  None    2026-07-09
1     {'times': 36.02241146332671, 'currency': 'btc'...    2026-07-09
2                                                  None    2026-07-09
3                                                  None    2026-07-09
4                                                  None    2026-07-09
...                                                 ...           ...
1245                                               None    2026-07-09
1246                                               None    2026-07-09
1247                                               None    2026-07-09
1248                                               None    2026-07-09
1249                                               None    2026-07-09

[1250 rows x 26 columns]
id                                          object
symbol                                      object
name                                        object
image                                       object
current_price                              float64
market_cap                                   int64
market_cap_rank                              int64
fully_diluted_valuation                      int64
total_volume                               float64
high_24h                                   float64
low_24h                                    float64
price_change_24h                           float64
price_change_percentage_24h                float64
market_cap_change_24h                      float64
market_cap_change_percentage_24h           float64
circulating_supply                         float64
total_supply                               float64
max_supply                                 float64
ath                                        float64
ath_change_percentage                      float64
ath_date                                    object
atl                                        float64
atl_change_percentage                      float64
atl_date                                    object
roi                                         object
last_updated                        datetime64[ns]
dtype: object

#Display the current data of crypto_df

In [8]:
crypto_df

,id,symbol,name,image,current_price,market_cap,market_cap_rank,fully_diluted_valuation,total_volume,high_24h,...,total_supply,max_supply,ath,ath_change_percentage,ath_date,atl,atl_change_percentage,atl_date,roi,last_updated
0,bitcoin,btc,Bitcoin,https://coin-images.coingecko.com/coins/images...,6021958.00,120780718016767,1,120780718016767,2.503460e+12,6027835.00,...,2.005413e+07,2.100000e+07,11187013.00,-46.16704,2025-10-06T18:57:42.558Z,3993.420000,1.507056e+05,2013-07-05T00:00:00.000Z,None,2026-07-09
1,ethereum,eth,Ethereum,https://coin-images.coingecko.com/coins/images...,166752.00,20125578725133,2,20125578725133,6.530638e+11,167541.00,...,1.206831e+08,NaN,431946.00,-61.39503,2025-08-24T19:21:03.333Z,28.130000,5.926662e+05,2015-10-20T00:00:00.000Z,"{'times': 36.02241146332671, 'currency': 'btc'...",2026-07-09
2,tether,usdt,Tether,https://coin-images.coingecko.com/coins/images...,95.30,17563324714594,3,18084324446422,3.771678e+12,95.85,...,1.897620e+11,NaN,105.52,-9.67283,2025-01-25T16:51:57.989Z,36.860000,1.585815e+02,2015-03-02T00:00:00.000Z,None,2026-07-09
3,binancecoin,bnb,BNB,https://coin-images.coingecko.com/coins/images...,54490.00,7344699722027,4,7344699722027,4.810700e+10,54828.00,...,1.347822e+08,2.000000e+08,121422.00,-55.12340,2025-10-13T08:41:24.131Z,2.580000,2.108047e+06,2017-10-19T00:00:00.000Z,None,2026-07-09
4,usd-coin,usdc,USDC,https://coin-images.coingecko.com/coins/images...,95.36,6993756631508,5,6993955746094,1.094599e+12,95.87,...,7.334406e+10,NaN,96.98,-1.66300,2026-05-20T14:19:58.071Z,65.310000,4.602658e+01,2021-05-19T13:14:05.611Z,None,2026-07-09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1245,astherus-usdf,usdf,Aster USDF,https://coin-images.coingecko.com/coins/images...,95.25,10786145973,246,10786145973,7.894920e+05,95.79,...,1.132437e+08,NaN,96.77,-1.56920,2026-05-20T14:15:24.188Z,70.870000,3.439748e+01,2025-10-10T21:23:15.100Z,None,2026-07-09
1246,spacex-bstocks-tokenized-stock,spcxb,SpaceX (bStocks Tokenized Stock),https://coin-images.coingecko.com/coins/images...,14539.76,10699479220,247,10699479220,3.744043e+09,14598.29,...,7.358696e+05,NaN,21458.00,-32.23964,2026-06-16T01:01:03.420Z,13918.180000,4.466850e+00,2026-07-08T18:56:43.802Z,None,2026-07-09
1247,derive,drv,Derive,https://coin-images.coingecko.com/coins/images...,10.59,10588239072,248,15886263406,3.318828e+07,10.70,...,1.500000e+09,1.500000e+09,19.75,-46.39283,2025-01-15T03:52:14.666Z,1.068000,8.918579e+02,2025-04-07T13:06:12.300Z,None,2026-07-09
1248,rollbit-coin,rlb,Rollbit Coin,https://coin-images.coingecko.com/coins/images...,6.50,10564333640,249,10564544316,2.602416e+07,6.56,...,1.624117e+09,5.000000e+09,22.02,-70.45862,2023-11-11T17:10:05.473Z,0.073824,8.711335e+03,2022-07-02T02:46:34.730Z,None,2026-07-09
1249,tradable-na-third-party-online-merchant-sstn,pc0000015,Tradable NA Third Party Online Merchant SSTN,https://coin-images.coingecko.com/coins/images...,95.38,10513798802,250,10513798802,NaN,95.93,...,1.102260e+08,3.500000e+08,97.01,-1.68005,2026-05-20T14:20:10.699Z,85.320000,1.179956e+01,2025-07-04T05:20:06.597Z,None,2026-07-09

#Display the length of the crypto_df

In [9]:
print(len(crypto_df))

1250

#2.Top 3 Coins – Historical Prices
#pick the top 3 from your dataset based on market_cap_rank
#Replace bitcoin with other coin IDs (e.g., ethereum, tether

In [10]:

import time
coins=['bitcoin','ethereum','tether']
records=[]
for i in coins:
    url=f"https://api.coingecko.com/api/v3/coins/{i}/market_chart?vs_currency=inr&days=365"
    response=requests.get(url)

    if response.status_code==200:
       data=response.json()
       print(i, response.status_code)

       #extracting price datas
       for price in data['prices']:
        records.append({'coin_id': i,
                        'date': pd.to_datetime(price[0], unit="ms").date(),
                        'price_inr': price[1]})
        print(f"{i}data fetched successfully")

    else:
        print(f"failed to fetch{i}")
        print("Status Code:", response.status_code)
        print(response.text)

    time.sleep(15)

bitcoin 200
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
bitcoindata fetched successfully
ethereum 200
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully
ethereumdata fetched successfully

#Pushing it to dataframe

In [11]:
coins_df=pd.DataFrame(records)
coins_df

      coin_id        date     price_inr
0     bitcoin  2025-07-10  9.541743e+06
1     bitcoin  2025-07-11  9.934948e+06
2     bitcoin  2025-07-12  1.009134e+07
3     bitcoin  2025-07-13  1.007829e+07
4     bitcoin  2025-07-14  1.022285e+07
...       ...         ...           ...
1093   tether  2026-07-06  9.512512e+01
1094   tether  2026-07-07  9.554551e+01
1095   tether  2026-07-08  9.553018e+01
1096   tether  2026-07-09  9.578381e+01
1097   tether  2026-07-09  9.528426e+01

[1098 rows x 3 columns]

#Checking data types of coins_df

In [ ]:
coins_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1098 entries, 0 to 1097
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   coin_id    1098 non-null   object
 1   date       1098 non-null   object
 2   price_inr  1098 non-null   float64
dtypes: float64(1), object(2)
memory usage: 25.9+ KB

#Checking length of the coins_df

In [12]:
len(coins_df)

1098

#Checking response of the coins

In [ ]:
coins = ["bitcoin", "ethereum", "tether"]

for coin in coins:
    url = f"https://api.coingecko.com/api/v3/coins/{coin}/market_chart?vs_currency=inr&days=365"

    response = requests.get(url)

    print(coin, response.status_code)

bitcoin 200
ethereum 429
tether 429

#converting data type from object to date

In [13]:
coins_df['date']=pd.to_datetime(coins_df['date'])
coins_df
coins_df.dtypes

coin_id              object
date         datetime64[ns]
price_inr           float64
dtype: object

#Retrive the coins_df

In [14]:
coins_df

      coin_id       date     price_inr
0     bitcoin 2025-07-10  9.541743e+06
1     bitcoin 2025-07-11  9.934948e+06
2     bitcoin 2025-07-12  1.009134e+07
3     bitcoin 2025-07-13  1.007829e+07
4     bitcoin 2025-07-14  1.022285e+07
...       ...        ...           ...
1093   tether 2026-07-06  9.512512e+01
1094   tether 2026-07-07  9.554551e+01
1095   tether 2026-07-08  9.553018e+01
1096   tether 2026-07-09  9.578381e+01
1097   tether 2026-07-09  9.528426e+01

[1098 rows x 3 columns]

#3.Oil prices

In [15]:
import pandas as pd
url='https://raw.githubusercontent.com/datasets/oil-prices/main/data/wti-daily.csv'
oil_df=pd.read_csv(url)
oil_df

             Date  Price
0      1986-01-02  25.56
1      1986-01-03  26.00
2      1986-01-06  26.53
3      1986-01-07  25.85
4      1986-01-08  25.87
...           ...    ...
10190  2026-06-29  71.87
10191  2026-06-30  70.56
10192  2026-07-01  69.74
10193  2026-07-02  69.73
10194  2026-07-06  69.60

[10195 rows x 2 columns]

#Checking the data type of oil_df

In [16]:
oil_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10195 entries, 0 to 10194
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    10195 non-null  object
 1   Price   10195 non-null  float64
dtypes: float64(1), object(1)
memory usage: 159.4+ KB

#Converting the Date type into date

In [17]:
oil_df['Date']=pd.to_datetime(oil_df['Date'])
oil_df
oil_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10195 entries, 0 to 10194
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    10195 non-null  datetime64[ns]
 1   Price   10195 non-null  float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 159.4 KB

#Filter date between 2020 to 2026

In [18]:
filter_df = oil_df[
    (oil_df["Date"] >= "2020-01-01") &
    (oil_df["Date"] <= "2026-12-31")
]

print(filter_df)

            Date  Price
8569  2020-01-02  61.17
8570  2020-01-03  63.00
8571  2020-01-06  63.27
8572  2020-01-07  62.70
8573  2020-01-08  59.65
...          ...    ...
10190 2026-06-29  71.87
10191 2026-06-30  70.56
10192 2026-07-01  69.74
10193 2026-07-02  69.73
10194 2026-07-06  69.60

[1626 rows x 2 columns]

#Checking length of the oil_df

In [19]:
len(oil_df)

10195

#4.Stock Prices (Yahoo Finance API)

In [20]:
import yfinance as yf
import pandas as pd

#choos indices

tickers=['^GSPC','^IXIC','^NSEI']
start_date='2020-01-01'
end_date='2026-03-09'

#Download historical data

stocks_df=yf.download(tickers,start=start_date,end=end_date,group_by='tickers')
stocks_df.head()

/tmp/ipykernel_578/1740541842.py:12: FutureWarning: YF.download() has changed argument auto_adjust default to True
  stocks_df=yf.download(tickers,start=start_date,end=end_date,group_by='tickers')
[*********************100%***********************]  3 of 3 completed

Ticker             ^NSEI                                                      \
Price               Open          High           Low         Close    Volume
Date
2020-01-01  12202.150391  12222.200195  12165.299805  12182.500000  304100.0
2020-01-02  12198.549805  12289.900391  12195.250000  12282.200195  407700.0
2020-01-03  12261.099609  12265.599609  12191.349609  12226.650391  428800.0
2020-01-06  12170.599609  12179.099609  11974.200195  11993.049805  396500.0
2020-01-07  12079.099609  12152.150391  12005.349609  12052.950195  447800.0

Ticker            ^GSPC                                                       \
Price              Open         High          Low        Close        Volume
Date
2020-01-01          NaN          NaN          NaN          NaN           NaN
2020-01-02  3244.669922  3258.139893  3235.530029  3257.850098  3.459930e+09
2020-01-03  3226.360107  3246.149902  3222.340088  3234.850098  3.484700e+09
2020-01-06  3217.550049  3246.840088  3214.639893  3246.280029  3.702460e+09
2020-01-07  3241.860107  3244.909912  3232.429932  3237.179932  3.435910e+09

Ticker            ^IXIC
Price              Open         High          Low        Close        Volume
Date
2020-01-01          NaN          NaN          NaN          NaN           NaN
2020-01-02  9039.459961  9093.429688  9010.889648  9092.190430  2.862700e+09
2020-01-03  8976.429688  9065.759766  8976.429688  9020.769531  2.586520e+09
2020-01-06  8943.500000  9072.410156  8943.500000  9071.469727  2.810450e+09
2020-01-07  9076.639648  9091.929688  9042.549805  9068.580078  2.381740e+09

#Checking the column names of stocks_df
#Sqlite doesn't support multi index column so have to convert into single index column

In [21]:
print(stocks_df.columns)
print(type(stocks_df.columns))

MultiIndex([('^NSEI',   'Open'),
            ('^NSEI',   'High'),
            ('^NSEI',    'Low'),
            ('^NSEI',  'Close'),
            ('^NSEI', 'Volume'),
            ('^GSPC',   'Open'),
            ('^GSPC',   'High'),
            ('^GSPC',    'Low'),
            ('^GSPC',  'Close'),
            ('^GSPC', 'Volume'),
            ('^IXIC',   'Open'),
            ('^IXIC',   'High'),
            ('^IXIC',    'Low'),
            ('^IXIC',  'Close'),
            ('^IXIC', 'Volume')],
           names=['Ticker', 'Price'])
<class 'pandas.core.indexes.multi.MultiIndex'>

#Converting the multi index column into single index column

In [22]:
stocks_df.columns = [
    f"{ticker}_{field}"
    for ticker, field in stocks_df.columns
]

stocks_df = stocks_df.reset_index()

#Checking the info of stocks_df whether it is modified or not(into sigle index)

In [23]:
stocks_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1603 entries, 0 to 1602
Data columns (total 16 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Date          1603 non-null   datetime64[ns]
 1   ^NSEI_Open    1530 non-null   float64
 2   ^NSEI_High    1530 non-null   float64
 3   ^NSEI_Low     1530 non-null   float64
 4   ^NSEI_Close   1530 non-null   float64
 5   ^NSEI_Volume  1530 non-null   float64
 6   ^GSPC_Open    1552 non-null   float64
 7   ^GSPC_High    1552 non-null   float64
 8   ^GSPC_Low     1552 non-null   float64
 9   ^GSPC_Close   1552 non-null   float64
 10  ^GSPC_Volume  1552 non-null   float64
 11  ^IXIC_Open    1552 non-null   float64
 12  ^IXIC_High    1552 non-null   float64
 13  ^IXIC_Low     1552 non-null   float64
 14  ^IXIC_Close   1552 non-null   float64
 15  ^IXIC_Volume  1552 non-null   float64
dtypes: datetime64[ns](1), float64(15)
memory usage: 200.5 KB

#Reset the particular ticker

In [ ]:
stocks_df['^NSEI'].reset_index()

Price,Date,Open,High,Low,Close,Volume
0,2020-01-01,12202.150391,12222.200195,12165.299805,12182.500000,304100.0
1,2020-01-02,12198.549805,12289.900391,12195.250000,12282.200195,407700.0
2,2020-01-03,12261.099609,12265.599609,12191.349609,12226.650391,428800.0
3,2020-01-06,12170.599609,12179.099609,11974.200195,11993.049805,396500.0
4,2020-01-07,12079.099609,12152.150391,12005.349609,12052.950195,447800.0
...,...,...,...,...,...,...
1598,2026-03-02,24659.250000,24989.349609,24603.500000,24865.699219,519200.0
1599,2026-03-03,NaN,NaN,NaN,NaN,NaN
1600,2026-03-04,24388.800781,24602.449219,24305.400391,24480.500000,599000.0
1601,2026-03-05,24615.949219,24854.199219,24529.400391,24765.900391,504300.0
1602,2026-03-06,24656.400391,24700.900391,24415.750000,24450.449219,433400.0

In [ ]:
stocks_df['^GSPC'].reset_index()

Price,Date,Open,High,Low,Close,Volume
0,2020-01-01,NaN,NaN,NaN,NaN,NaN
1,2020-01-02,3244.669922,3258.139893,3235.530029,3257.850098,3.459930e+09
2,2020-01-03,3226.360107,3246.149902,3222.340088,3234.850098,3.484700e+09
3,2020-01-06,3217.550049,3246.840088,3214.639893,3246.280029,3.702460e+09
4,2020-01-07,3241.860107,3244.909912,3232.429932,3237.179932,3.435910e+09
...,...,...,...,...,...,...
1598,2026-03-02,6824.359863,6901.009766,6796.850098,6881.620117,6.079080e+09
1599,2026-03-03,6800.259766,6840.049805,6710.419922,6816.629883,6.442080e+09
1600,2026-03-04,6831.689941,6885.939941,6811.640137,6869.500000,5.252170e+09
1601,2026-03-05,6851.080078,6870.430176,6770.779785,6830.709961,5.989300e+09
1602,2026-03-06,6769.029785,6773.419922,6711.560059,6740.020020,5.793120e+09

In [ ]:
stocks_df['^IXIC'].reset_index()

Price,Date,Open,High,Low,Close,Volume
0,2020-01-01,NaN,NaN,NaN,NaN,NaN
1,2020-01-02,9039.459961,9093.429688,9010.889648,9092.190430,2.862700e+09
2,2020-01-03,8976.429688,9065.759766,8976.429688,9020.769531,2.586520e+09
3,2020-01-06,8943.500000,9072.410156,8943.500000,9071.469727,2.810450e+09
4,2020-01-07,9076.639648,9091.929688,9042.549805,9068.580078,2.381740e+09
...,...,...,...,...,...,...
1598,2026-03-02,22322.119141,22802.800781,22306.080078,22748.859375,8.303030e+09
1599,2026-03-03,22292.369141,22601.589844,22124.779297,22516.689453,9.705500e+09
1600,2026-03-04,22620.890625,22891.880859,22570.669922,22807.480469,1.091841e+10
1601,2026-03-05,22707.470703,22877.019531,22500.289062,22748.990234,1.099466e+10
1602,2026-03-06,22421.169922,22614.410156,22328.130859,22387.679688,9.300220e+09

#Concating 03 stocks

In [ ]:
dfs = []

for ticker in tickers:
    df = stocks_df[ticker].copy()      # Get one ticker's data
    df.reset_index(inplace=True)       # Convert Date index to column
    df["Ticker"] = ticker              # Add ticker name
    dfs.append(df)

# Concatenate all three DataFrames
final_df = pd.concat(dfs, ignore_index=True)

print(final_df.head().reset_index)

<bound method DataFrame.reset_index of Price       Date         Open         High          Low        Close  \
0     2020-01-01          NaN          NaN          NaN          NaN
1     2020-01-02  3244.669922  3258.139893  3235.530029  3257.850098
2     2020-01-03  3226.360107  3246.149902  3222.340088  3234.850098
3     2020-01-06  3217.550049  3246.840088  3214.639893  3246.280029
4     2020-01-07  3241.860107  3244.909912  3232.429932  3237.179932

Price        Volume Ticker
0               NaN  ^GSPC
1      3.459930e+09  ^GSPC
2      3.484700e+09  ^GSPC
3      3.702460e+09  ^GSPC
4      3.435910e+09  ^GSPC  >

#//end
#Created and collected 4 types of datas

#Creating database and Connecting to sqlite

In [24]:
import sqlite3
conn=sqlite3.connect('cross_market_analysis.db')
cursor=conn.cursor()

#inserting collected datas into sqlite

In [25]:
coins_df.to_sql('coins_data',if_exists='replace',con=conn)

1098

In [26]:
oil_df.to_sql('oil_data',if_exists='replace',con=conn)

10195

In [27]:
stocks_df.to_sql('stocks_data',conn,if_exists='replace',index=False)

1603

#To delete current database(If needed)

In [ ]:
import os

conn = sqlite3.connect("cross_market_analysis.db")

# Perform database operations...

conn.close()      # Close the connection

os.remove("cross_market_analysis.db")

print("Database deleted.")

Database deleted.

#crypto_df converting dic into json format for sql connection
#Sqlite doesn't support dictionary format

In [28]:
import json

for col in crypto_df.columns:
    crypto_df[col] = crypto_df[col].apply(
        lambda x: json.dumps(x) if isinstance(x, dict) else x
    )

In [29]:
crypto_df.to_sql('crypto_df',if_exists='replace',con=conn,index=False)

1250

#Reading pushed datas

In [30]:
pd.read_sql('select * from crypto_df',con=conn)

,id,symbol,name,image,current_price,market_cap,market_cap_rank,fully_diluted_valuation,total_volume,high_24h,...,total_supply,max_supply,ath,ath_change_percentage,ath_date,atl,atl_change_percentage,atl_date,roi,last_updated
0,bitcoin,btc,Bitcoin,https://coin-images.coingecko.com/coins/images...,6021958.00,120780718016767,1,120780718016767,2.503460e+12,6027835.00,...,2.005413e+07,2.100000e+07,11187013.00,-46.16704,2025-10-06T18:57:42.558Z,3993.420000,1.507056e+05,2013-07-05T00:00:00.000Z,None,2026-07-09 00:00:00
1,ethereum,eth,Ethereum,https://coin-images.coingecko.com/coins/images...,166752.00,20125578725133,2,20125578725133,6.530638e+11,167541.00,...,1.206831e+08,NaN,431946.00,-61.39503,2025-08-24T19:21:03.333Z,28.130000,5.926662e+05,2015-10-20T00:00:00.000Z,"{""times"": 36.02241146332671, ""currency"": ""btc""...",2026-07-09 00:00:00
2,tether,usdt,Tether,https://coin-images.coingecko.com/coins/images...,95.30,17563324714594,3,18084324446422,3.771678e+12,95.85,...,1.897620e+11,NaN,105.52,-9.67283,2025-01-25T16:51:57.989Z,36.860000,1.585815e+02,2015-03-02T00:00:00.000Z,None,2026-07-09 00:00:00
3,binancecoin,bnb,BNB,https://coin-images.coingecko.com/coins/images...,54490.00,7344699722027,4,7344699722027,4.810700e+10,54828.00,...,1.347822e+08,2.000000e+08,121422.00,-55.12340,2025-10-13T08:41:24.131Z,2.580000,2.108047e+06,2017-10-19T00:00:00.000Z,None,2026-07-09 00:00:00
4,usd-coin,usdc,USDC,https://coin-images.coingecko.com/coins/images...,95.36,6993756631508,5,6993955746094,1.094599e+12,95.87,...,7.334406e+10,NaN,96.98,-1.66300,2026-05-20T14:19:58.071Z,65.310000,4.602658e+01,2021-05-19T13:14:05.611Z,None,2026-07-09 00:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1245,astherus-usdf,usdf,Aster USDF,https://coin-images.coingecko.com/coins/images...,95.25,10786145973,246,10786145973,7.894920e+05,95.79,...,1.132437e+08,NaN,96.77,-1.56920,2026-05-20T14:15:24.188Z,70.870000,3.439748e+01,2025-10-10T21:23:15.100Z,None,2026-07-09 00:00:00
1246,spacex-bstocks-tokenized-stock,spcxb,SpaceX (bStocks Tokenized Stock),https://coin-images.coingecko.com/coins/images...,14539.76,10699479220,247,10699479220,3.744043e+09,14598.29,...,7.358696e+05,NaN,21458.00,-32.23964,2026-06-16T01:01:03.420Z,13918.180000,4.466850e+00,2026-07-08T18:56:43.802Z,None,2026-07-09 00:00:00
1247,derive,drv,Derive,https://coin-images.coingecko.com/coins/images...,10.59,10588239072,248,15886263406,3.318828e+07,10.70,...,1.500000e+09,1.500000e+09,19.75,-46.39283,2025-01-15T03:52:14.666Z,1.068000,8.918579e+02,2025-04-07T13:06:12.300Z,None,2026-07-09 00:00:00
1248,rollbit-coin,rlb,Rollbit Coin,https://coin-images.coingecko.com/coins/images...,6.50,10564333640,249,10564544316,2.602416e+07,6.56,...,1.624117e+09,5.000000e+09,22.02,-70.45862,2023-11-11T17:10:05.473Z,0.073824,8.711335e+03,2022-07-02T02:46:34.730Z,None,2026-07-09 00:00:00
1249,tradable-na-third-party-online-merchant-sstn,pc0000015,Tradable NA Third Party Online Merchant SSTN,https://coin-images.coingecko.com/coins/images...,95.38,10513798802,250,10513798802,NaN,95.93,...,1.102260e+08,3.500000e+08,97.01,-1.68005,2026-05-20T14:20:10.699Z,85.320000,1.179956e+01,2025-07-04T05:20:06.597Z,None,2026-07-09 00:00:00

In [31]:
pd.read_sql('select * from stocks_data',con=conn)

,Date,^NSEI_Open,^NSEI_High,^NSEI_Low,^NSEI_Close,^NSEI_Volume,^GSPC_Open,^GSPC_High,^GSPC_Low,^GSPC_Close,^GSPC_Volume,^IXIC_Open,^IXIC_High,^IXIC_Low,^IXIC_Close,^IXIC_Volume
0,2020-01-01 00:00:00,12202.150391,12222.200195,12165.299805,12182.500000,304100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2020-01-02 00:00:00,12198.549805,12289.900391,12195.250000,12282.200195,407700.0,3244.669922,3258.139893,3235.530029,3257.850098,3.459930e+09,9039.459961,9093.429688,9010.889648,9092.190430,2.862700e+09
2,2020-01-03 00:00:00,12261.099609,12265.599609,12191.349609,12226.650391,428800.0,3226.360107,3246.149902,3222.340088,3234.850098,3.484700e+09,8976.429688,9065.759766,8976.429688,9020.769531,2.586520e+09
3,2020-01-06 00:00:00,12170.599609,12179.099609,11974.200195,11993.049805,396500.0,3217.550049,3246.840088,3214.639893,3246.280029,3.702460e+09,8943.500000,9072.410156,8943.500000,9071.469727,2.810450e+09
4,2020-01-07 00:00:00,12079.099609,12152.150391,12005.349609,12052.950195,447800.0,3241.860107,3244.909912,3232.429932,3237.179932,3.435910e+09,9076.639648,9091.929688,9042.549805,9068.580078,2.381740e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1598,2026-03-02 00:00:00,24659.250000,24989.349609,24603.500000,24865.699219,519200.0,6824.359863,6901.009766,6796.850098,6881.620117,6.079080e+09,22322.119141,22802.800781,22306.080078,22748.859375,8.303030e+09
1599,2026-03-03 00:00:00,NaN,NaN,NaN,NaN,NaN,6800.259766,6840.049805,6710.419922,6816.629883,6.442080e+09,22292.369141,22601.589844,22124.779297,22516.689453,9.705500e+09
1600,2026-03-04 00:00:00,24388.800781,24602.449219,24305.400391,24480.500000,599000.0,6831.689941,6885.939941,6811.640137,6869.500000,5.252170e+09,22620.890625,22891.880859,22570.669922,22807.480469,1.091841e+10
1601,2026-03-05 00:00:00,24615.949219,24854.199219,24529.400391,24765.900391,504300.0,6851.080078,6870.430176,6770.779785,6830.709961,5.989300e+09,22707.470703,22877.019531,22500.289062,22748.990234,1.099466e+10
1602,2026-03-06 00:00:00,24656.400391,24700.900391,24415.750000,24450.449219,433400.0,6769.029785,6773.419922,6711.560059,6740.020020,5.793120e+09,22421.169922,22614.410156,22328.130859,22387.679688,9.300220e+09

In [32]:
pd.read_sql('select * from oil_data',con=conn)

       index                 Date  Price
0          0  1986-01-02 00:00:00  25.56
1          1  1986-01-03 00:00:00  26.00
2          2  1986-01-06 00:00:00  26.53
3          3  1986-01-07 00:00:00  25.85
4          4  1986-01-08 00:00:00  25.87
...      ...                  ...    ...
10190  10190  2026-06-29 00:00:00  71.87
10191  10191  2026-06-30 00:00:00  70.56
10192  10192  2026-07-01 00:00:00  69.74
10193  10193  2026-07-02 00:00:00  69.73
10194  10194  2026-07-06 00:00:00  69.60

[10195 rows x 3 columns]

In [33]:
pd.read_sql('select * from coins_data',con=conn)

      index  coin_id                 date     price_inr
0         0  bitcoin  2025-07-10 00:00:00  9.541743e+06
1         1  bitcoin  2025-07-11 00:00:00  9.934948e+06
2         2  bitcoin  2025-07-12 00:00:00  1.009134e+07
3         3  bitcoin  2025-07-13 00:00:00  1.007829e+07
4         4  bitcoin  2025-07-14 00:00:00  1.022285e+07
...     ...      ...                  ...           ...
1093   1093   tether  2026-07-06 00:00:00  9.512512e+01
1094   1094   tether  2026-07-07 00:00:00  9.554551e+01
1095   1095   tether  2026-07-08 00:00:00  9.553018e+01
1096   1096   tether  2026-07-09 00:00:00  9.578381e+01
1097   1097   tether  2026-07-09 00:00:00  9.528426e+01

[1098 rows x 4 columns]

#Streamli setup

In [34]:
!pip install -q streamlit
!wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
!chmod +x cloudflared-linux-amd64
import subprocess
subprocess.Popen(["./cloudflared-linux-amd64", "tunnel", "--url", "http://localhost:8501"])
!nohup /content/cloudflared-linux-amd64 tunnel --url http://localhost:8501 &

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.3/10.3 MB 92.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.4/11.4 MB 100.8 MB/s eta 0:00:00
--2026-07-09 18:11:09--  https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
Resolving github.com (github.com)... 140.82.113.3
Connecting to github.com (github.com)|140.82.113.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://github.com/cloudflare/cloudflared/releases/download/2026.7.1/cloudflared-linux-amd64 [following]
--2026-07-09 18:11:09--  https://github.com/cloudflare/cloudflared/releases/download/2026.7.1/cloudflared-linux-amd64
Reusing existing connection to github.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://release-assets.githubusercontent.com/github-production-release-asset/106867604/84b7d829-7d74-4679-b2dd-09368a130047?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-07-09T19%3A00%3A44Z&rscd=attachment%3B+filename%3Dcloudflared-linux-amd64&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-07-09T18%3A00%3A29Z&ske=2026-07-09T19%3A00%3A44Z&sks=b&skv=2018-11-09&sig=lZ81LDjur1LP%2B1YLaOtftbZgRGirQ6zgKn1rqi0iAuo%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc4MzYyMjM3OCwibmJmIjoxNzgzNjIwNTc4LCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.CxL7osPHIXPrVoNH9z8UeBt0osfdqzVzJrFKlEsQ15s&response-content-disposition=attachment%3B%20filename%3Dcloudflared-linux-amd64&response-content-type=application%2Foctet-stream [following]
--2026-07-09 18:11:10--  https://release-assets.githubusercontent.com/github-production-release-asset/106867604/84b7d829-7d74-4679-b2dd-09368a130047?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-07-09T19%3A00%3A44Z&rscd=attachment%3B+filename%3Dcloudflared-linux-amd64&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-07-09T18%3A00%3A29Z&ske=2026-07-09T19%3A00%3A44Z&sks=b&skv=2018-11-09&sig=lZ81LDjur1LP%2B1YLaOtftbZgRGirQ6zgKn1rqi0iAuo%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc4MzYyMjM3OCwibmJmIjoxNzgzNjIwNTc4LCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.CxL7osPHIXPrVoNH9z8UeBt0osfdqzVzJrFKlEsQ15s&response-content-disposition=attachment%3B%20filename%3Dcloudflared-linux-amd64&response-content-type=application%2Foctet-stream
Resolving release-assets.githubusercontent.com (release-assets.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to release-assets.githubusercontent.com (release-assets.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 39251522 (37M) [application/octet-stream]
Saving to: ‘cloudflared-linux-amd64’

cloudflared-linux-a 100%[===================>]  37.43M   190MB/s    in 0.2s

2026-07-09 18:11:10 (190 MB/s) - ‘cloudflared-linux-amd64’ saved [39251522/39251522]

nohup: appending output to 'nohup.out'

#Installing streamlit option menu

In [35]:
pip install streamlit-option_menu

Collecting streamlit-option_menu
  Downloading streamlit_option_menu-0.4.0-py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: streamlit>=1.36 in /usr/local/lib/python3.12/dist-packages (from streamlit-option_menu) (1.59.1)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option_menu) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option_menu) (1.9.0)
Requirement already satisfied: cachetools<8,>=5.5 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option_menu) (6.2.6)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option_menu) (8.4.2)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option_menu) (3.1.50)
Requirement already satisfied: numpy<3,>=1.23 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option_menu) (2.0.2)
Requirement already satisfied: packaging>=20 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option_menu) (26.2)
Requirement already satisfied: pandas<4,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option_menu) (2.2.2)
Requirement already satisfied: pillow<13,>=7.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option_menu) (11.3.0)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option_menu) (0.9.3)
Requirement already satisfied: protobuf<8,>=3.20 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option_menu) (5.29.6)
Requirement already satisfied: pyarrow>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option_menu) (18.1.0)
Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option_menu) (2.32.4)
Requirement already satisfied: tenacity<10,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option_menu) (9.1.4)
Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option_menu) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option_menu) (4.15.0)
Requirement already satisfied: starlette>=0.40.0 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option_menu) (1.3.1)
Requirement already satisfied: uvicorn>=0.30.0 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option_menu) (0.49.0)
Requirement already satisfied: httptools>=0.6.3 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option_menu) (0.8.0)
Requirement already satisfied: anyio>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option_menu) (4.14.0)
Requirement already satisfied: python-multipart>=0.0.10 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option_menu) (0.0.32)
Requirement already satisfied: websockets>=12.0.0 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option_menu) (15.0.1)
Requirement already satisfied: itsdangerous>=2.1.2 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option_menu) (2.2.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option_menu) (6.0.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit>=1.36->streamlit-option_menu) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit>=1.36->streamlit-option_menu) (4.26.0)
Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit>=1.36->streamlit-option_menu) (2.22.1)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio>=4.0.0->streamlit>=1.36->streamlit-option_menu) (3.18)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit>=1.36->streamlit-option_menu) (4.0.12)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<4,>=1.4.0->streamlit>=1.36->streamlit-option_menu) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<4,>=1.4.0->streamlit>=1.36->streamlit-option_menu) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<4,>=1.4.0->streamlit>=1.36->streamlit-option_menu) (2026.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit>=1.36->streamlit-option_menu) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit>=1.36->streamlit-option_menu) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit>=1.36->streamlit-option_menu) (2026.6.17)
Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.12/dist-packages (from uvicorn>=0.30.0->streamlit>=1.36->streamlit-option_menu) (0.16.0)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit>=1.36->streamlit-option_menu) (5.0.3)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit>=1.36->streamlit-option_menu) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit>=1.36->streamlit-option_menu) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit>=1.36->streamlit-option_menu) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit>=1.36->streamlit-option_menu) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit>=1.36->streamlit-option_menu) (2026.5.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<4,>=1.4.0->streamlit>=1.36->streamlit-option_menu) (1.17.0)
Downloading streamlit_option_menu-0.4.0-py3-none-any.whl (829 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 829.3/829.3 kB 19.1 MB/s eta 0:00:00
Installing collected packages: streamlit-option_menu
Successfully installed streamlit-option_menu-0.4.0

#Creating and configuring the new streamlit file

In [40]:
%%writefile crossmarketanalysis.py

import streamlit as st
import sqlite3
import pandas as pd
from streamlit_option_menu import option_menu

# Connecting to sql

conn=sqlite3.connect('cross_market_analysis.db')
cursor=conn.cursor()

st.title('CROSS MARKET ANALYSIS')
st.divider()

with st.sidebar:
    selected = option_menu(
    'Main Menu',
    ['Market Overview', 'SQL Query Runner', 'Top 03 Crypto Analysis'],
    icons=['house', 'database', 'currency-bitcoin'],
    menu_icon='cast',
    default_index=0
)
if selected=='Market Overview':
  st.title('Welcome to market overview')

  col1, col2 = st.columns(2)

  with col1:
        start_date = st.date_input("Start Date")

  with col2:
        end_date = st.date_input("End Date")

#coin avg price

  query = """
  SELECT ROUND(AVG(price_inr),2) AS bitcoin_avg
  FROM coins_data
  WHERE coin_id='bitcoin'
  AND date BETWEEN ? AND ?;
  """

  bitcoin_avg = pd.read_sql_query(
    query,
    conn,
    params=(start_date, end_date))

  btc_avg = bitcoin_avg.iloc[0]["bitcoin_avg"]

  st.write(bitcoin_avg)


#Oil average

  query = """
  SELECT ROUND(AVG(price),2) AS oil_avg
  FROM oil_data
  WHERE date BETWEEN ? AND ?;
  """

  oil_avg = pd.read_sql_query(
    query,
    conn,
    params=(start_date, end_date))

  oil_price = oil_avg.iloc[0]["oil_avg"]

  st.write(oil_avg)

#SP average

  query = """
  SELECT ROUND(AVG("^GSPC_Close"),2) AS sp500_avg
  FROM stocks_data
  WHERE Date between ? AND ?;
  """

  sp500_avg = pd.read_sql_query(
    query,
    conn,
    params=(start_date, end_date))

  sp500 = sp500_avg.iloc[0]["sp500_avg"]

  st.write(sp500_avg)

#NIFTY average

  query = """
  SELECT ROUND(AVG("^NSEI_Close"),2) AS nifty_avg
  FROM stocks_data
  WHERE Date BETWEEN ? AND ?;
  """

  nifty_avg = pd.read_sql_query(
    query,
    conn,
    params=(start_date, end_date))

  nifty = nifty_avg.iloc[0]["nifty_avg"]

  st.write(nifty_avg)

#Display snapchat

  query = """
  SELECT
    c.date,
    ROUND(c.price_inr,2) AS Bitcoin,
    ROUND(o.price,2) AS Oil,
    ROUND(s."^GSPC_Close",2) AS SP500,
    ROUND(s."^NSEI_Close",2) AS NIFTY
  FROM coins_data c
  INNER JOIN oil_data o
  ON c.date = o.date
  INNER JOIN stocks_data s
  ON c.date = s.Date
  WHERE c.coin_id='bitcoin'
  AND c.date BETWEEN ? AND ?
  ORDER BY c.date;
  """

  snapshot_df = pd.read_sql_query(
    query,
    conn,
    params=(start_date, end_date))

  st.subheader("Daily Market Snapshot")
  st.dataframe(snapshot_df, use_container_width=True)


elif selected == "SQL Query Runner":

  st.title('Welcome to sql runner')

  query_option = {
      "crypto(1).Find the top 3 cryptocurrencies by market cap":
      """SELECT id,MAX(market_cap) AS market_cap from crypto_df group by id order by market_cap desc limit 3""",

      "crypto(2).List all coins where circulating supply exceeds 90% of total supply":
      """ SELECT id,circulating_supply from crypto_df
      where circulating_supply>total_supply*0.9 group by id
      order by circulating_supply desc""",

      "crypto(3).Get coins that are within 10% of their all-time-high":
      """SELECT DISTINCT
      id,
      ROUND(current_price, 2) AS current_price,
      ROUND(ath, 2) AS all_time_high,
      ROUND((current_price / ath) * 100, 2) AS pct_of_ath
      FROM crypto_df
      WHERE ath > 0
      AND current_price >= 0.9 * ath
      ORDER BY pct_of_ath DESC;""",

      "crypto(4).Find the avg market cap rank of coins with volume above 1B":
      """SELECT id, AVG(market_cap_rank) AS avg_market_cap_rank
      FROM crypto_df
      WHERE total_volume > 1000000000 group by id order by market_cap_rank desc;""",

      "crypto(5).Get the most recently updated coin":
      """SELECT id,last_updated from crypto_df order by last_updated desc limit 1;""",

      "coins(6).Find the highest daily price of Bitcoin in the last 365 days":
      """SELECT MAX(price_inr) AS highest_price
      FROM coins_data
      WHERE coin_id = 'bitcoin'
      AND date >= DATE('now', '-1 year');""",

      "coins(7).Calculate the average daily price of Ethereum in the past 1 year":
      """SELECT AVG(price_inr) AS avg_price
      FROM coins_data
      WHERE coin_id = 'ethereum'
      AND date >= DATE('now', '-1 year');""",

      "coins(8).Show the daily price trend of Bitcoin in January 2026":
      """SELECT date, price_inr
      FROM coins_data
      WHERE coin_id = 'bitcoin'
      AND date BETWEEN '2026-01-01' AND '2026-01-31';""",

      "coins(9).Find the coin with the highest average price over 1 year":
      """SELECT coin_id, AVG(price_inr) AS avg_price
      FROM coins_data
      GROUP BY coin_id
      ORDER BY avg_price DESC
      LIMIT 1;""",

      "coins(10).Get the % change in Bitcoin’s price between Sep 2024 and Sep 2025":
      """SELECT (price_inr - LAG(price_inr) OVER (ORDER BY date)) / LAG(price_inr) OVER (ORDER BY date) * 100 AS price_change
      FROM coins_data
      WHERE coin_id = 'bitcoin'
      AND date BETWEEN '2024-09-01' AND '2025-09-30';""",

      "oil(11).Find the highest oil price in the last 5 years":
      """SELECT MAX(price) AS highest_price
      FROM oil_data
      WHERE Date >= DATE('now', '-5 years');""",

      "oil(12).Get the average oil price per year":
      """SELECT strftime('%Y', Date) AS year, AVG(price) AS avg_price
      FROM oil_data
      GROUP BY year
      ORDER BY year;""",

      "oil(13).Show oil prices during COVID crash (March–April 2020)":
      """SELECT Date, price
      FROM oil_data
      WHERE Date BETWEEN '2020-01-01' AND '2020-04-30';""",

      "oil(14).Find the lowest price of oil in the last 10 years":
      """SELECT MIN(price) AS lowest_price
      FROM oil_data
      WHERE Date >= DATE('now', '-10 years');""",

      "oil(15).Calculate the volatility of oil prices (max-min difference per year)":
      """SELECT strftime('Y', Date) AS year, MAX(price), MIN(price), MAX(price) - MIN(price) AS volatility
      FROM oil_data
      GROUP BY year
      ORDER BY year;""",

      "stocks(16).Get all stock prices for a given ticker":
      """SELECT Date, ROUND("^GSPC_Close",2) AS SP500, ROUND("^NSEI_Close",2) AS NIFTY,
      ROUND("^IXIC_Close",2) AS NASDAQ
      FROM stocks_data
      WHERE Date BETWEEN '2025-01-01' AND '2026-01-31';""",

      "stocks(17).Find the highest closing price for NASDAQ (^IXIC)":
      """SELECT MAX("^IXIC_Close") AS highest_price
      FROM stocks_data;""",

      "stocks(18).List top 5 days with highest price difference (high - low) for S&P 500 (^GSPC)":
      """SELECT Date, ROUND("^GSPC_High",2) - ROUND("^GSPC_Low",2) AS price_diff
      FROM stocks_data
      ORDER BY price_diff DESC
      LIMIT 5;""",

      "stocks(19).Get monthly average closing price for each ticker":
      """SELECT strftime('%Y-%m', Date) AS month,
      ROUND(AVG("^GSPC_Close"),2) AS SP500,
      ROUND(AVG("^NSEI_Close"),2) AS NIFTY,
      ROUND(AVG("^IXIC_Close"),2) AS NASDAQ
      FROM stocks_data
      GROUP BY month
      ORDER BY month;""",

      "stocks(20).Get average trading volume of NSEI in 2024":
      """SELECT AVG("^NSEI_Volume") AS avg_volume
      FROM stocks_data
      WHERE Date BETWEEN '2024-01-01' AND '2024-12-31';""",

      "joins(21).Compare Bitcoin vs Oil average price in 2025":
      """SELECT ROUND(AVG(c.price_inr),2) AS bitcoin_avg,
      ROUND(AVG(o.price),2) AS oil_avg
      FROM coins_data c
      INNER JOIN oil_data o
      ON c.date = o.date
      WHERE c.date BETWEEN '2025-01-01' AND '2025-12-31';""",

      "joins(22).Check if Bitcoin moves with S&P 500 (correlation idea)":
      """SELECT ROUND(AVG(c.price_inr),2) AS bitcoin_avg,
      ROUND(AVG(s."^GSPC_Close"),2) AS sp500_avg
      FROM coins_data c
      INNER JOIN stocks_data s
      ON c.date = s.Date
      WHERE c.coin_id='bitcoin';""",

      "joins(23).Compare Ethereum and NASDAQ daily prices for 2025":
      """SELECT ROUND(AVG(c.price_inr),2) AS ethereum_avg,
      ROUND(AVG(s."^IXIC_Close"),2) AS nasdaq_avg
      FROM coins_data c
      INNER JOIN stocks_data s
      ON c.date = s.Date
      WHERE c.coin_id='ethereum'
      AND c.date BETWEEN '2025-01-01' AND '2025-12-31';""",

      "joins(24).Find days when oil price spiked and compare with Bitcoin price change":
      """SELECT
      o.Date,
      ROUND(o.Price, 2) AS oil_price,
      ROUND(c.price_inr, 2) AS bitcoin_price
      FROM oil_data o
      JOIN coins_data c
      ON o.Date = c.date
      WHERE c.coin_id = 'bitcoin'
      ORDER BY o.Date;""",

      "joins(25).Compare top 3 coins daily price trend vs Nifty (^NSEI)":
      """SELECT c.date,
      ROUND(c.price_inr,2) AS bitcoin,
      ROUND(c.price_inr,2) AS ethereum,
      ROUND(c.price_inr,2) AS dogecoin,
      ROUND(s."^NSEI_Close",2) AS nifty
      FROM coins_data c
      INNER JOIN stocks_data s
      ON c.date = s.Date
      WHERE c.date BETWEEN '2025-01-01' AND '2025-12-31'
      ORDER BY c.date;""",

      "joins(26).Compare stock prices (^GSPC) with crude oil prices on the same dates":
      """SELECT s."^GSPC_Close", o.price
      FROM stocks_data s
      INNER JOIN oil_data o
      ON s.Date = o.Date
      WHERE s.Date BETWEEN '2025-01-01' AND '2025-12-31';""",

      "joins(27).Correlate Bitcoin closing price with crude oil closing price (same date)":
      """SELECT c.date, ROUND(AVG(c.price_inr),2) AS bitcoin_avg,
      ROUND(AVG(o.price),2) AS oil_avg
      FROM coins_data c
      INNER JOIN oil_data o
      ON c.date = o.Date
      WHERE c.coin_id='bitcoin' group by c.date limit 1;""",

      "joins(28).Compare NASDAQ (^IXIC) with Ethereum price trends":
      """SELECT c.date, ROUND(AVG(c.price_inr),2) AS ethereum_avg,
      ROUND(AVG(s."^IXIC_Close"),2) AS nasdaq_avg
      FROM coins_data c
      INNER JOIN stocks_data s
      ON c.date = s.Date
      WHERE c.coin_id = 'ethereum' GROUP BY c.date;""",

      "joins(29).Join top 3 crypto coins with stock indices for 2025":
      """SELECT c.date,
      ROUND(c.price_inr,2) AS bitcoin,
      ROUND(c.price_inr,2) AS ethereum,
      ROUND(c.price_inr,2) AS dogecoin,
      ROUND(s."^GSPC_Close",2) AS sp500,
      ROUND(s."^NSEI_Close",2) AS nifty,
      ROUND(s."^IXIC_Close",2) AS nasdaq
      FROM coins_data c
      INNER JOIN stocks_data s
      ON c.date = s.Date
      WHERE c.date BETWEEN '2025-01-01' AND '2025-12-31'
      ORDER BY c.date;""",

      "joins(30).Multi-join: stock prices, oil prices, and Bitcoin prices for daily comparison":
      """SELECT s.Date,
      ROUND(s."^GSPC_Close",2) AS sp500,
      ROUND(s."^NSEI_Close",2) AS nifty,
      ROUND(s."^IXIC_Close",2) AS nasdaq,
      ROUND(o.price,2) AS oil_price,
      ROUND(c.price_inr,2) AS bitcoin_price
      FROM stocks_data s
      INNER JOIN oil_data o
      ON s.Date = o.Date
      INNER JOIN coins_data c
      ON s.Date = c.date
      WHERE c.coin_id = 'bitcoin'
      ORDER BY s.Date;"""

  }
  option = st.selectbox("Select a query to execute:", list(query_option.keys()))

  if st.button("Run Query"):
        try:
            result_df = pd.read_sql_query(query_option[option], conn)
            st.dataframe(result_df, use_container_width=True)
        except Exception as e:
            st.error(f"Query failed: {e}")

elif selected == "Top 03 Crypto Analysis":
    st.title('Welcome to Top 03 Crypto Analysis')

    # --- Get list of available coins (Top 3) ---
    coins_df = pd.read_sql("SELECT DISTINCT coin_id FROM coins_data", con=conn)
    coin_list = coins_df['coin_id'].tolist()

    selected_coin = st.selectbox("Select a Cryptocurrency", coin_list)

    # --- Get min/max date for that coin, to bound the date picker ---
    date_range = pd.read_sql(
        "SELECT MIN(date) as min_date, MAX(date) as max_date FROM coins_data WHERE coin_id = ?",
        con=conn,
        params=(selected_coin,)
    )
    min_date = pd.to_datetime(date_range['min_date'][0])
    max_date = pd.to_datetime(date_range['max_date'][0])

    # --- Date range picker (safely handled) ---
    date_selection = st.date_input(
        "Select Date Range",
        value=(min_date, max_date),
        min_value=min_date,
        max_value=max_date
    )

    # Guard against the case where only one date has been picked so far
    if not isinstance(date_selection, tuple) or len(date_selection) != 2:
        st.warning("Please select both a start and end date.")
        st.stop()

    start_date, end_date = date_selection

    # Push end date to end-of-day so BETWEEN includes the full last day
    start_date_str = str(start_date) + " 00:00:00"
    end_date_str = str(end_date) + " 23:59:59"

    # --- Query filtered data ---
    query = """
    SELECT date, price_inr
    FROM coins_data
    WHERE coin_id = ?
    AND date BETWEEN ? AND ?
    ORDER BY date;
    """
    df = pd.read_sql(query, con=conn, params=(selected_coin, start_date_str, end_date_str))

    if df.empty:
        st.warning("No data available for the selected coin and date range.")
    else:
        df['date'] = pd.to_datetime(df['date'])

        # --- Line chart (optional per spec, but included) ---
        st.subheader(f"{selected_coin.capitalize()} Price Trend")
        st.line_chart(df.set_index('date')['price_inr'])

        # --- Data table ---
        st.subheader("Daily Price Table")
        st.dataframe(
            df.rename(columns={'date': 'Date', 'price_inr': 'Price (INR)'}),
            use_container_width=True
        )

Overwriting crossmarketanalysis.py

Delete exist streamlit

In [41]:
!streamlit run /content/crossmarketanalysis.py &>/content/logs.txt &

In [42]:
!grep -o 'https://.*\.trycloudflare.com' nohup.out | head -n 1 | xargs -I {} echo "Your tunnel url {}"

Your tunnel url https://lions-legs-destinations-tracking.trycloudflare.com